[workspace]
members = ["./src/*", "./task/*"]
default-members = ["src/cli"]
resolver = "3"

[workspace.package]
authors = ["Leo Borai <estebanborai@gmail.com>"]
version = "0.0.0-pre.6a3850b"
edition = "2024"
categories = ["web-programming"]
description = "🦀🧡🧉"
documentation = "https://docs.rs/wasmq"
keywords = ["job", "queue", "scheduler", "wasm"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/LeoBorai/wasmq"
readme = "./README.md"

[workspace.dependencies]
anyhow = "1.0"
async-trait = "0.1"
axum = "0.8"
bytes = "1.11"
chrono = "0.4"
clap = "4.6"
humantime = "2.3"
include_dir = "0.7"
log = "0.4"
proc-macro2 = "1.0"
reqwest = "0.13"
semver = { version = "1.0", features = ["serde"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
sqlx = "0.9.0"
syn = { version = "2.0", features = ["full", "extra-traits"] }
quote = "1.0"
rustls = "0.23"
tabled = "0.20"
tempfile = "3.27"
tokio = "1"
toml = "1.0"
tracing = "0.1"
tracing-subscriber = "0.3"
ulid = "1.2"
wasmtime = "44.0"
wasmtime-wasi = "44.0"
wasmtime-wasi-http = "44.0"
wit-bindgen = "0.57"
wstd = "0.6"

wasmq-config = { path = "./src/config" }
wasmq-executor = { path = "./src/executor" }
wasmq-ipc = { path = "./src/ipc" }
wasmq = { path = "./src/wasmq" }
wasmq-repository = { path = "./src/repository" }
wasmq-scheduler = { path = "./src/scheduler" }
wasmq-storage = { path = "./src/storage" }
wasmq-task = { path = "./src/task" }
