[package]
name = "wasmq-repository"
edition.workspace = true
version.workspace = true
authors.workspace = true
description.workspace = true
documentation.workspace = true

[lib]
name = "wasmq_repository"
path = "src/lib.rs"

[dependencies]
anyhow = { workspace = true }
async-trait = { workspace = true }
bytes = { workspace = true }
serde = { workspace = true, features = ["derive"] }
semver = { workspace = true }
tokio = { workspace = true, features = ["fs", "io-std", "io-util"] }

wasmq = { workspace = true }
