[package]
name = "{{WASMQ_TASK_NAME}}"
authors = ["{{WASMQ_TASK_AUTHOR}}"]
version = "{{WASMQ_TASK_VERSION}}"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
anyhow = "1.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
wit-bindgen = "0.51"

wasmq-task = "0.0.0-pre.b8589f5"
