[package]
name = "wasmq-scheduler"
edition.workspace = true
version.workspace = true
authors.workspace = true
description.workspace = true
documentation.workspace = true

[lib]
name = "wasmq_scheduler"
path = "src/lib.rs"

[dependencies]
anyhow = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
ulid = { workspace = true }

wasmq = { workspace = true }
wasmq-ipc = { workspace = true }
